# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3a3cb9c4f62d9a981fbfb064e9552819651106648dbf429dd1bc6a22ec9ff334f202fb1bc6f9ef01989d3c5eb296ee350235ed6d8c30c3c3f3dadddce71a3e

test:
  secret_key_base: f3ee3b22dc7d93b80780edc98aab969505410e8bdd6547441d5260841a71a42767ff78eef23c97622a72fba3a266ba910444868f494c983f3c75e46422947c15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
